# Generated by Django 5.2 on 2025-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_beneficiario_alter_customuser_ci_cuentabancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ci',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
