# Generated by Django 5.2 on 2025-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_customuser_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='numero_cuenta',
            field=models.IntegerField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=21),
        ),
    ]
