# Generated by Django 5.2 on 2025-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_cuentabancaria_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='numero_cuenta',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
