# Generated by Django 5.2 on 2025-05-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_alter_cuentabancaria_numero_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
